=== folio-org/mod-inventory/ramls/holdings-record.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "A holdings record",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "the system assigned unique ID of the holdings record; UUID",
      "$ref": "./uuid.json"
    },
    "_version": {
      "type": "integer",
      "description": "Record version for optimistic locking"
    },
    "hrid": {
      "type": "string",
      "description": "the human readable ID, also called eye readable ID. A system-assigned sequential ID which maps to the Instance ID"
    },
    "holdingsTypeId": {
      "type": "string",
      "description": "unique ID for the type of this holdings record, a UUID",
      "$ref": "./uuid.json"
    },
    "formerIds": {
      "type": "array",
      "description": "Previous ID(s) assigned to the holdings record",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "instanceId": {
      "description": "Instance id",
      "type": "string",
      "$ref": "./uuid.json"
    },
    "permanentLocationId": {
      "type": "string",
      "description": "The permanent shelving location in which an item resides.",
      "$ref": "./uuid.json"
    },
    "temporaryLocationId": {
      "type": "string",
      "description": "Temporary location is the temporary location, shelving location, or holding which is a physical place where items are stored, or an Online location.",
      "$ref": "./uuid.json"
    },
    "effectiveLocationId": {
      "type": "string",
      "description": "Effective location is calculated by the system based on the values in the permanent and temporary locationId fields.",
      "$ref": "./uuid.json"
    },
    "electronicAccess": {
      "description": "Electronic access",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "uri": {
            "type": "string",
            "description": "uniform resource identifier (URI) is a string of characters designed for unambiguous identification of resources"
          },
          "linkText": {
            "type": "string",
            "description": "the value of the MARC tag field 856 2nd indicator, where the values are: no information provided, resource, version of resource, related resource, no display constant generated"
          },
          "materialsSpecification": {
            "type": "string",
            "description": "materials specified is used to specify to what portion or aspect of the resource the electronic location and access information applies (e.g. a portion or subset of the item is electronic, or a related electronic resource is being linked to the record)"
          },
          "publicNote": {
            "type": "string",
            "description": "URL public note to be displayed in the discovery"
          },
          "relationshipId": {
            "type": "string",
            "description": "relationship between the electronic resource at the location identified and the item described in the record as a whole"
          }
        },
        "additionalProperties": false,
        "required": [
          "uri"
        ]
      }
    },
    "additionalCallNumbers": {
      "description": "Additional Call Numbers to track the history of identifiers assigned to an item.",
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "additionalCallNumber.json",
        "uniqueItems": true
        }
    },
    "callNumberTypeId": {
      "type": "string",
      "description": "unique ID for the type of call number on a holdings record, a UUID",
      "$ref": "./uuid.json"
    },
    "callNumberPrefix": {
      "type": "string",
      "description": "Prefix of the call number on the holding level."
    },
    "callNumber": {
      "type": "string",
      "description": "Call Number is an identifier assigned to an item, usually printed on a label attached to the item."
    },
    "callNumberSuffix": {
      "type": "string",
      "description": "Suffix of the call number on the holding level."
    },
    "shelvingTitle": {
      "type": "string",
      "description": "Indicates the shelving form of title."
    },
    "acquisitionFormat": {
      "description": "Acquisition format",
      "type": "string"
    },
    "acquisitionMethod": {
      "description": "Acquisition method",
      "type": "string"
    },
    "receiptStatus": {
      "type": "string",
      "description": "Receipt status (e.g. pending, awaiting receipt, partially received, fully received, receipt not required, and cancelled)"
    },
    "notes": {
      "description": "Notes about action, copy, binding etc.",
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "holdings-notes.json"
      }
    },
    "illPolicyId": {
      "type": "string",
      "description": "unique ID for an ILL policy, a UUID",
      "$ref": "./uuid.json"
    },
    "retentionPolicy": {
      "type": "string",
      "description": "Records information regarding how long we have agreed to keep something."
    },
    "digitizationPolicy": {
      "description": "Digitization policy",
      "type": "string"
    },
    "holdingsStatements": {
      "type": "array",
      "description": "Holdings statements",
      "items": {
        "type": "object",
        "properties": {
          "statement": {
            "type": "string",
            "description": "Specifices the exact content to which the library has access, typically for continuing publications."
          },
          "note": {
            "type": "string",
            "description": "Note attached to a holdings statement"
          },
          "staffNote": {
            "type": "string",
            "description": "Private note attached to a holdings statement"
          }
        }
      }
    },
    "holdingsStatementsForIndexes": {
      "description": "Holdings statements for indexes",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "statement": {
            "type": "string",
            "description": "Textual description of the holdings of indexes"
          },
          "note": {
            "type": "string",
            "description": "Note attached to a holdings statement"
          },
          "staffNote": {
            "type": "string",
            "description": "Private note attached to a holdings statement"
          }
        }
      }
    },
    "holdingsStatementsForSupplements": {
      "description": "Holdings statements for supplements",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "statement": {
            "type": "string",
            "description": "textual description of the holdings of supplementary material"
          },
          "note": {
            "type": "string",
            "description": "note attached to a holdings statement"
          },
          "staffNote": {
            "type": "string",
            "description": "Private note attached to a holdings statement"
          }
        }
      }
    },
    "copyNumber": {
      "type": "string",
      "description": "Item/Piece ID (usually barcode) for systems that do not use item records. Ability to designate the copy number if institution chooses to use copy numbers."
    },
    "numberOfItems": {
      "type": "string",
      "description": "Text (Number)"
    },
    "receivingHistory": {
      "description": "Receiving history",
      "type": "object",
      "properties": {
        "displayType": {
          "type": "string",
          "description": "Display hint. 1: Display fields separately. 2: Display fields concatenated"
        },
        "entries": {
          "type": "array",
          "description": "Entries",
          "items": {
            "type": "object",
            "properties": {
              "publicDisplay": {
                "type": "boolean",
                "description": "Defines if the receivingHistory should be visible to the public."
              },
              "enumeration": {
                "type": "string",
                "description": "This is the volume/issue number (e.g. v.71:no.6-2)"
              },
              "chronology": {
                "type": "string",
                "description": "Repeated element from Receiving history - Enumeration AND Receiving history - Chronology"
              }
            }
          }
        }
      }
    },
    "discoverySuppress": {
      "type": "boolean",
      "description": "records the fact that the record should not be displayed in a discovery system"
    },
    "administrativeNotes":{
      "type": "array",
      "description": "Administrative notes",
      "minItems": 0,
      "items": {
        "type": "string"
      }
    },
    "statisticalCodeIds": {
      "type": "array",
      "description": "List of statistical code IDs",
      "items": {
        "type": "string",
        "$ref": "./uuid.json"
      },
      "uniqueItems": true
    },
    "holdingsInstance": {
      "description": "Holdings Instance",
      "type": "object",
      "folio:$ref": "instance.json",
      "readonly": true,
      "folio:isVirtual": true,
      "folio:linkBase": "inventory/instances",
      "folio:linkFromField": "instanceId",
      "folio:linkToField": "id",
      "folio:includedElement": "instances.0"
    },
    "tags": {
      "description": "arbitrary tags associated with this holding",
      "id": "tags",
      "type": "object",
      "$ref": "./raml-util/schemas/tags.schema"
    },
    "sourceId": {
      "description": "UUID of the holdings records source",
      "type": "string",
      "$ref": "uuid.json"
    },
    "metadata": {
      "type": "object",
      "$ref": "./raml-util/schemas/metadata.schema",
      "readonly": true
    }
  },
  "additionalProperties": false,
  "required": [
    "instanceId",
    "permanentLocationId"
  ]
}

=== folio-org/mod-inventory/src/test/resources/handlers/holdings.json
{
  "id": "65cb2bf0-d4c2-4886-8ad0-b76f1ba75d61",
  "instanceId": "cd28da0f-a3e4-465c-82f1-acade4e8e170",
  "permanentLocationId": "d9cd0bed-1b49-4b5e-a7bd-064b8d177231",
  "holdingsStatements": [
    {
      "statement": "Line 1",
      "note": "Note to line 1"
    },
    {
      "statement": "Line 2",
      "note": "Note to line2"
    }
  ],
  "tags" : {
    "tagList" : [
      "important"
    ]
  },
  "metadata" : {
    "createdDate" : "1970-01-01T00:00:00.000+00:00",
    "createdByUserId" : "b22b1169-5a4e-488d-a5f1-8900900dcoffe",
    "updatedDate" : "1995-05-23T14:27:46.245+00:00",
    "updatedByUserId" : "b22b1169-5a4e-488d-a5f1-8900900dcoffe"
  }
}
